### ISSUE TITLE
Write up - Time comparison, Challenges or difficulties

### ISSUE THREAD

**Issue by imtvwy** [UBC-MDS/DSCI_525_Group25#7]

**Comment by Anupriya-Sri** [comment]
Challenges from my side: (1) The memory required for processing was very high (512 MB, 1 GB) and we were getting error messages while combining the files and converting file format. So, we had to close all the other applications, incl. Slack, to run the code.
(2) The notebook crashed multiple times and the system would hang after that. So, we restarted the machine every time we ran into error
